// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type execmonEvent struct {
	_          structs.HostLayout
	Pid        uint32
	Ppid       uint32
	CgroupId   uint64
	Comm       [16]uint8
	ParentComm [16]uint8
	Filename   [256]uint8
}

// loadExecmon returns the embedded CollectionSpec for execmon.
func loadExecmon() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecmonBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load execmon: %w", err)
	}

	return spec, err
}

// loadExecmonObjects loads execmon and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*execmonObjects
//	*execmonPrograms
//	*execmonMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadExecmonObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadExecmon()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// execmonSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execmonSpecs struct {
	execmonProgramSpecs
	execmonMapSpecs
	execmonVariableSpecs
}

// execmonProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execmonProgramSpecs struct {
	OnProcessExec *ebpf.ProgramSpec `ebpf:"on_process_exec"`
}

// execmonMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execmonMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// execmonVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execmonVariableSpecs struct {
	UnusedEvent *ebpf.VariableSpec `ebpf:"unused_event"`
}

// execmonObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadExecmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type execmonObjects struct {
	execmonPrograms
	execmonMaps
	execmonVariables
}

func (o *execmonObjects) Close() error {
	return _ExecmonClose(
		&o.execmonPrograms,
		&o.execmonMaps,
	)
}

// execmonMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadExecmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type execmonMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *execmonMaps) Close() error {
	return _ExecmonClose(
		m.Events,
	)
}

// execmonVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadExecmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type execmonVariables struct {
	UnusedEvent *ebpf.Variable `ebpf:"unused_event"`
}

// execmonPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadExecmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type execmonPrograms struct {
	OnProcessExec *ebpf.Program `ebpf:"on_process_exec"`
}

func (p *execmonPrograms) Close() error {
	return _ExecmonClose(
		p.OnProcessExec,
	)
}

func _ExecmonClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed execmon_bpfel.o
var _ExecmonBytes []byte
