// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type filemonEvent struct {
	_        structs.HostLayout
	Pid      uint32
	Flags    uint32
	CgroupId uint64
	Comm     [16]uint8
	Filename [256]uint8
}

// loadFilemon returns the embedded CollectionSpec for filemon.
func loadFilemon() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FilemonBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load filemon: %w", err)
	}

	return spec, err
}

// loadFilemonObjects loads filemon and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*filemonObjects
//	*filemonPrograms
//	*filemonMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFilemonObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFilemon()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// filemonSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filemonSpecs struct {
	filemonProgramSpecs
	filemonMapSpecs
	filemonVariableSpecs
}

// filemonProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filemonProgramSpecs struct {
	OnOpenat *ebpf.ProgramSpec `ebpf:"on_openat"`
}

// filemonMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filemonMapSpecs struct {
	DroppedEvents *ebpf.MapSpec `ebpf:"dropped_events"`
	Events        *ebpf.MapSpec `ebpf:"events"`
}

// filemonVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filemonVariableSpecs struct {
	UnusedEvent *ebpf.VariableSpec `ebpf:"unused_event"`
}

// filemonObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFilemonObjects or ebpf.CollectionSpec.LoadAndAssign.
type filemonObjects struct {
	filemonPrograms
	filemonMaps
	filemonVariables
}

func (o *filemonObjects) Close() error {
	return _FilemonClose(
		&o.filemonPrograms,
		&o.filemonMaps,
	)
}

// filemonMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFilemonObjects or ebpf.CollectionSpec.LoadAndAssign.
type filemonMaps struct {
	DroppedEvents *ebpf.Map `ebpf:"dropped_events"`
	Events        *ebpf.Map `ebpf:"events"`
}

func (m *filemonMaps) Close() error {
	return _FilemonClose(
		m.DroppedEvents,
		m.Events,
	)
}

// filemonVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFilemonObjects or ebpf.CollectionSpec.LoadAndAssign.
type filemonVariables struct {
	UnusedEvent *ebpf.Variable `ebpf:"unused_event"`
}

// filemonPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFilemonObjects or ebpf.CollectionSpec.LoadAndAssign.
type filemonPrograms struct {
	OnOpenat *ebpf.Program `ebpf:"on_openat"`
}

func (p *filemonPrograms) Close() error {
	return _FilemonClose(
		p.OnOpenat,
	)
}

func _FilemonClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed filemon_bpfeb.o
var _FilemonBytes []byte
