// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type netmonEvent struct {
	_        structs.HostLayout
	Pid      uint32
	_        [4]byte
	CgroupId uint64
	DstPort  uint16
	DstIp    [4]uint8
	Comm     [16]uint8
	_        [2]byte
}

// loadNetmon returns the embedded CollectionSpec for netmon.
func loadNetmon() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetmonBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load netmon: %w", err)
	}

	return spec, err
}

// loadNetmonObjects loads netmon and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*netmonObjects
//	*netmonPrograms
//	*netmonMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetmonObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetmon()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// netmonSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netmonSpecs struct {
	netmonProgramSpecs
	netmonMapSpecs
	netmonVariableSpecs
}

// netmonProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netmonProgramSpecs struct {
	OnConnect *ebpf.ProgramSpec `ebpf:"on_connect"`
}

// netmonMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netmonMapSpecs struct {
	DroppedEvents *ebpf.MapSpec `ebpf:"dropped_events"`
	Events        *ebpf.MapSpec `ebpf:"events"`
}

// netmonVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netmonVariableSpecs struct {
	UnusedEvent *ebpf.VariableSpec `ebpf:"unused_event"`
}

// netmonObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type netmonObjects struct {
	netmonPrograms
	netmonMaps
	netmonVariables
}

func (o *netmonObjects) Close() error {
	return _NetmonClose(
		&o.netmonPrograms,
		&o.netmonMaps,
	)
}

// netmonMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type netmonMaps struct {
	DroppedEvents *ebpf.Map `ebpf:"dropped_events"`
	Events        *ebpf.Map `ebpf:"events"`
}

func (m *netmonMaps) Close() error {
	return _NetmonClose(
		m.DroppedEvents,
		m.Events,
	)
}

// netmonVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type netmonVariables struct {
	UnusedEvent *ebpf.Variable `ebpf:"unused_event"`
}

// netmonPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type netmonPrograms struct {
	OnConnect *ebpf.Program `ebpf:"on_connect"`
}

func (p *netmonPrograms) Close() error {
	return _NetmonClose(
		p.OnConnect,
	)
}

func _NetmonClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netmon_bpfeb.o
var _NetmonBytes []byte
